#!/bin/sh

dunst &
flameshot &
nm-applet &
redshift-gtk &
caffeine &
slstatus &
sxhkd &
picom &
protonmail-bridge --no-window &

autorandr -c
feh --bg-fill /usr/share/backgrounds/wallpaper.png

exec dwm
