#!/bin/sh

set -e

sound_card="alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic"
selected_profile=$(pactl --format=json list cards | jq -r --arg card $sound_card '.[] | select(.name == $card) | .profiles | keys[]' | dmenu -i -l 5)
pactl set-card-profile "$sound_card" "$selected_profile"
